version: '3'
networks:
    appNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.21.0.0/16"
services:
  mongodb:
    image: mongo
    container_name: "database"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db        
    networks:
       appNetwork:
          ipv4_address: 172.21.0.2
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
       appNetwork:
          ipv4_address: 172.21.0.8
    restart: unless-stopped
volumes:
  mongodb_data: